-- migrate:up
INSERT INTO cities (id, province_id, name, type) VALUES
(24,2,'Asahan','KABUPATEN'),
(25,2,'Batu Bara','KABUPATEN'),
(26,2,'Dairi','KABUPATEN'),
(27,2,'Deli Serdang','KABUPATEN'),
(28,2,'Humbang Hasundutan','KABUPATEN'),
(29,2,'Karo','KABUPATEN'),
(30,2,'Labuhanbatu','KABUPATEN'),
(31,2,'Labuhanbatu Selatan','KABUPATEN'),
(32,2,'Labuhanbatu Utara','KABUPATEN'),
(33,2,'Langkat','KABUPATEN'),
(34,2,'Mandailing Natal','KABUPATEN'),
(35,2,'Nias','KABUPATEN'),
(36,2,'Nias Barat','KABUPATEN'),
(37,2,'Nias Selatan','KABUPATEN'),
(38,2,'Nias Utara','KABUPATEN'),
(39,2,'Padang Lawas','KABUPATEN'),
(40,2,'Padang Lawas Utara','KABUPATEN'),
(41,2,'Pakpak Bharat','KABUPATEN'),
(42,2,'Samosir','KABUPATEN'),
(43,2,'Serdang Bedagai','KABUPATEN'),
(44,2,'Simalungun','KABUPATEN'),
(45,2,'Tapanuli Selatan','KABUPATEN'),
(46,2,'Tapanuli Tengah','KABUPATEN'),
(47,2,'Tapanuli Utara','KABUPATEN'),
(48,2,'Toba','KABUPATEN'),
(49,2,'Binjai','KOTA'),
(50,2,'Gunungsitoli','KOTA'),
(51,2,'Medan','KOTA'),
(52,2,'Padangsidimpuan','KOTA'),
(53,2,'Pematangsiantar','KOTA'),
(54,2,'Sibolga','KOTA'),
(55,2,'Tanjungbalai','KOTA'),
(56,2,'Tebing Tinggi','KOTA');

-- migrate:down
