-- migrate:up
CREATE TABLE cities (
  id INT PRIMARY KEY,
  province_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  type ENUM('KABUPATEN','KOTA') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (province_id) REFERENCES provinces(id)
);

-- migrate:down
DROP TABLE IF EXISTS cities;