-- migrate:up
INSERT INTO provinces (id, name, code) VALUES
(1, 'Aceh', 'ID-AC'),
(2, 'Sumatera Utara', 'ID-SU'),
(3, 'Sumatera Barat', 'ID-SB'),
(4, 'Riau', 'ID-RI'),
(5, 'Jambi', 'ID-JA'),
(6, 'Sumatera Selatan', 'ID-SS'),
(7, 'Bengkulu', 'ID-BE'),
(8, 'Lampung', 'ID-LA'),
(9, 'Kepulauan Bangka Belitung', 'ID-BB'),
(10, 'Kepulauan Riau', 'ID-KR'),
(11, 'DKI Jakarta', 'ID-JK'),
(12, 'Jawa Barat', 'ID-JB'),
(13, 'Jawa Tengah', 'ID-JT'),
(14, 'DI Yogyakarta', 'ID-YO'),
(15, 'Jawa Timur', 'ID-JI'),
(16, 'Banten', 'ID-BT'),
(17, 'Bali', 'ID-BA'),
(18, 'Nusa Tenggara Barat', 'ID-NB'),
(19, 'Nusa Tenggara Timur', 'ID-NT'),
(20, 'Kalimantan Barat', 'ID-KB'),
(21, 'Kalimantan Tengah', 'ID-KT'),
(22, 'Kalimantan Selatan', 'ID-KS'),
(23, 'Kalimantan Timur', 'ID-KI'),
(24, 'Kalimantan Utara', 'ID-KU'),
(25, 'Sulawesi Utara', 'ID-SA'),
(26, 'Sulawesi Tengah', 'ID-ST'),
(27, 'Sulawesi Selatan', 'ID-SN'),
(28, 'Sulawesi Tenggara', 'ID-SG'),
(29, 'Gorontalo', 'ID-GO'),
(30, 'Sulawesi Barat', 'ID-SR'),
(31, 'Maluku', 'ID-MA'),
(32, 'Maluku Utara', 'ID-MU'),
(33, 'Papua', 'ID-PA'),
(34, 'Papua Barat', 'ID-PB'),
(35, 'Papua Selatan', 'ID-PS'),
(36, 'Papua Tengah', 'ID-PT'),
(37, 'Papua Pegunungan', 'ID-PE'),
(38, 'Papua Barat Daya', 'ID-PD');
-- migrate:down

