-- migrate:up
CREATE TABLE statuses (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  status VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE IF NOT EXISTS statuses